ALTER TABLE files
    ADD COLUMN IF NOT EXISTS width_px INTEGER,
    ADD COLUMN IF NOT EXISTS height_px INTEGER,
    ADD COLUMN IF NOT EXISTS duration_ms BIGINT,
    ADD COLUMN IF NOT EXISTS thumbnail_key TEXT;

